services:
  db:
    image: postgres:latest
    container_name: bankbills_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bankbills_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bankbills_api
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_HTTP_PORTS=8000
      - ASPNETCORE_ENVIROMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=bankbills_db;Username=postgres;Password=admin
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: